# Generated by Django 3.0.3 on 2020-03-03 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garde_name', models.CharField(max_length=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(upload_to='')),
                ('pub_date', models.DateField()),
                ('topic_body', models.TextField()),
                ('topic_title', models.CharField(max_length=50)),
                ('grade_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Grade')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=10)),
                ('date_of_joining', models.DateField()),
                ('date_of_birth', models.DateField()),
                ('mother_tongue', models.CharField(max_length=10)),
                ('nationality', models.CharField(max_length=10)),
                ('grade_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Grade')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_joining', models.DateField()),
                ('subject_handling', models.CharField(max_length=10)),
                ('grade_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='staff.Grade')),
                ('staff_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_income', models.IntegerField()),
                ('occupation', models.CharField(max_length=10)),
                ('parent_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('student_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='staff.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Message_track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Grade')),
                ('message_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Message')),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Parent')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Status')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Staff'),
        ),
    ]
