# Generated by Django 3.0.3 on 2020-03-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20200303_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file_path',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
