# Generated by Django 3.0.3 on 2020-03-06 16:36

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import staff.validators


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20200303_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('staff.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='grade',
            name='description',
            field=models.TextField(validators=[staff.validators.highvaluelength]),
        ),
        migrations.AlterField(
            model_name='grade',
            name='garde_name',
            field=models.CharField(max_length=10, validators=[staff.validators.valuelength]),
        ),
        migrations.AlterField(
            model_name='message',
            name='topic_body',
            field=models.TextField(validators=[staff.validators.highvaluelength]),
        ),
        migrations.AlterField(
            model_name='message',
            name='topic_title',
            field=models.CharField(max_length=50, validators=[staff.validators.valuelength]),
        ),
        migrations.AlterField(
            model_name='parent',
            name='monthly_income',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='parent',
            name='occupation',
            field=models.CharField(max_length=10, validators=[staff.validators.valuelength]),
        ),
        migrations.AlterField(
            model_name='staff',
            name='subject_handling',
            field=models.CharField(max_length=10, validators=[staff.validators.valuelength]),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_name',
            field=models.CharField(max_length=10, validators=[staff.validators.valuelength]),
        ),
        migrations.AlterField(
            model_name='student',
            name='mother_tongue',
            field=models.CharField(max_length=10, validators=[staff.validators.valuelength]),
        ),
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'only alphabet is allowed'), staff.validators.valuelength]),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'only alphabet is allowed'), staff.validators.valuelength]),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(default=None, max_length=100, validators=[staff.validators.highvaluelength]),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(validators=[staff.validators.highvaluelength]),
        ),
    ]
