# Generated by Django 3.0.3 on 2020-03-06 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_auto_20200306_1636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userproxy',
            options={'verbose_name': 'New Request', 'verbose_name_plural': 'New Requests'},
        ),
    ]
